/* Catálogo base de exercícios e fichas de exemplo.
   Cada exercício: id, nome, grupo, equipamento, tipo ('forca' | 'cardio'). */

const GRUPOS = ['Peito','Costas','Pernas','Ombros','Bíceps','Tríceps','Abdómen','Cardio'];

/* Dias da semana, com domingo em 0 — como no getDay() do JavaScript. */
const LETRAS_DIA = ['D','S','T','Q','Q','S','S'];
// Como se chamam os treinos de um programa, quando a IA não lhes dá letra.
const LETRAS_TREINO = ['A','B','C','D','E','F','G','H'];
const NOMES_DIA = ['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'];

const EXERCICIOS_BASE = [
  // Peito
  { id:'suo-reto',      nome:'Supino reto com barra',        grupo:'Peito',   equip:'Barra' },
  { id:'sup-incl-hal',  nome:'Supino inclinado com halteres',grupo:'Peito',   equip:'Halteres' },
  { id:'sup-decl',      nome:'Supino declinado',             grupo:'Peito',   equip:'Barra' },
  { id:'crucifixo',     nome:'Crucifixo com halteres',       grupo:'Peito',   equip:'Halteres' },
  { id:'crossover',     nome:'Crossover na polia',           grupo:'Peito',   equip:'Polia' },
  { id:'flexao',        nome:'Flexão de braço',              grupo:'Peito',   equip:'Peso corporal' },
  { id:'peck-deck',     nome:'Peck deck (voador)',           grupo:'Peito',   equip:'Máquina' },

  // Costas
  { id:'barra-fixa',    nome:'Barra fixa',                   grupo:'Costas',  equip:'Peso corporal' },
  { id:'puxada-frente', nome:'Puxada frontal',               grupo:'Costas',  equip:'Polia' },
  { id:'remada-curv',   nome:'Remada curvada com barra',     grupo:'Costas',  equip:'Barra' },
  { id:'remada-uni',    nome:'Remada unilateral (serrote)',  grupo:'Costas',  equip:'Halteres' },
  { id:'remada-baixa',  nome:'Remada baixa na polia',        grupo:'Costas',  equip:'Polia' },
  { id:'levantamento',  nome:'Levantamento terra',           grupo:'Costas',  equip:'Barra' },
  { id:'pulldown',      nome:'Pullover na polia',            grupo:'Costas',  equip:'Polia' },

  // Pernas
  { id:'agachamento',   nome:'Agachamento livre',            grupo:'Pernas',  equip:'Barra' },
  { id:'leg-press',     nome:'Leg press 45°',                grupo:'Pernas',  equip:'Máquina' },
  { id:'ext-joelhos',   nome:'Cadeira extensora',            grupo:'Pernas',  equip:'Máquina' },
  { id:'flex-joelhos',  nome:'Mesa flexora',                 grupo:'Pernas',  equip:'Máquina' },
  { id:'stiff',         nome:'Stiff com barra',              grupo:'Pernas',  equip:'Barra' },
  { id:'afundo',        nome:'Afundo com halteres',          grupo:'Pernas',  equip:'Halteres' },
  { id:'bulgaro',       nome:'Agachamento búlgaro',          grupo:'Pernas',  equip:'Halteres' },
  { id:'panturrilha',   nome:'Gémeos em pé',            grupo:'Pernas',  equip:'Máquina' },
  { id:'hip-thrust',    nome:'Elevação pélvica (hip thrust)',grupo:'Pernas',  equip:'Barra' },
  { id:'cadeira-abd',   nome:'Cadeira abdutora',             grupo:'Pernas',  equip:'Máquina' },

  // Ombros
  { id:'desenvolv',     nome:'Desenvolvimento com halteres', grupo:'Ombros',  equip:'Halteres' },
  { id:'desenvolv-mil', nome:'Desenvolvimento militar',      grupo:'Ombros',  equip:'Barra' },
  { id:'elev-lateral',  nome:'Elevação lateral',             grupo:'Ombros',  equip:'Halteres' },
  { id:'elev-frontal',  nome:'Elevação frontal',             grupo:'Ombros',  equip:'Halteres' },
  { id:'crucifixo-inv', nome:'Crucifixo inverso',            grupo:'Ombros',  equip:'Halteres' },
  { id:'remada-alta',   nome:'Remada alta',                  grupo:'Ombros',  equip:'Barra' },
  { id:'encolhimento',  nome:'Encolhimento de ombros',       grupo:'Ombros',  equip:'Halteres' },

  // Bíceps
  { id:'rosca-direta',  nome:'Rosca direta com barra',       grupo:'Bíceps',  equip:'Barra' },
  { id:'rosca-alt',     nome:'Rosca alternada',              grupo:'Bíceps',  equip:'Halteres' },
  { id:'rosca-martelo', nome:'Rosca martelo',                grupo:'Bíceps',  equip:'Halteres' },
  { id:'rosca-scott',   nome:'Rosca scott',                  grupo:'Bíceps',  equip:'Máquina' },
  { id:'rosca-conc',    nome:'Rosca concentrada',            grupo:'Bíceps',  equip:'Halteres' },

  // Tríceps
  { id:'triceps-polia', nome:'Tríceps na polia (corda)',     grupo:'Tríceps', equip:'Polia' },
  { id:'triceps-testa', nome:'Tríceps testa',                grupo:'Tríceps', equip:'Barra' },
  { id:'triceps-franc', nome:'Tríceps francês',              grupo:'Tríceps', equip:'Halteres' },
  { id:'mergulho',      nome:'Mergulho no banco',            grupo:'Tríceps', equip:'Peso corporal' },
  { id:'paralelas',     nome:'Paralelas',                    grupo:'Tríceps', equip:'Peso corporal' },

  // Abdómen
  { id:'prancha',       nome:'Prancha isométrica',           grupo:'Abdómen', equip:'Peso corporal' },
  { id:'abd-supra',     nome:'Abdominal',              grupo:'Abdómen', equip:'Peso corporal' },
  { id:'elev-pernas',   nome:'Elevação de pernas',           grupo:'Abdómen', equip:'Peso corporal' },
  { id:'abd-obliquo',   nome:'Abdominal oblíquo',            grupo:'Abdómen', equip:'Peso corporal' },
  { id:'roda-abd',      nome:'Roda abdominal',               grupo:'Abdómen', equip:'Acessório' },

  // Cardio
  { id:'esteira',       nome:'Passadeira',                      grupo:'Cardio',  equip:'Máquina', tipo:'cardio' },
  { id:'bike',          nome:'Bicicleta',        grupo:'Cardio',  equip:'Máquina', tipo:'cardio' },
  { id:'eliptico',      nome:'Elíptica',                     grupo:'Cardio',  equip:'Máquina', tipo:'cardio' },
  { id:'corda',         nome:'Saltar à corda',                  grupo:'Cardio',  equip:'Acessório', tipo:'cardio' },
  { id:'remo-ergo',     nome:'Remo',               grupo:'Cardio',  equip:'Máquina', tipo:'cardio' },

  /* --- Catálogo alargado: 251 exercícios, todos com figura de execução.
     Nomes em português de Portugal; grupo e equipamento traduzidos para
     os que a app já usava. --- */
  { id:'weighted-crunch', nome:'Abdominal com disco', grupo:'Abdómen', equip:'Acessório' },
  { id:'reverse-crunch', nome:'Abdominal invertido', grupo:'Abdómen', equip:'Peso corporal' },
  { id:'cable-crunch', nome:'Abdominal na polia', grupo:'Abdómen', equip:'Polia' },
  { id:'decline-sit-up', nome:'Abdominal no banco declinado', grupo:'Abdómen', equip:'Peso corporal' },
  { id:'mountain-climber', nome:'Alpinista', grupo:'Abdómen', equip:'Peso corporal' },
  { id:'bird-dog', nome:'Bird dog', grupo:'Abdómen', equip:'Peso corporal' },
  { id:'dead-bug', nome:'Dead bug', grupo:'Abdómen', equip:'Peso corporal' },
  { id:'banded-dead-bug', nome:'Dead bug com elástico', grupo:'Abdómen', equip:'Elástico' },
  { id:'dragon-flag', nome:'Dragon flag', grupo:'Abdómen', equip:'Peso corporal' },
  { id:'captains-chair-knee-raise', nome:'Elevação de joelhos na cadeira romana', grupo:'Abdómen', equip:'Máquina' },
  { id:'hanging-knee-raise', nome:'Elevação de joelhos suspenso', grupo:'Abdómen', equip:'Peso corporal' },
  { id:'hanging-leg-raise', nome:'Elevação de pernas suspenso', grupo:'Abdómen', equip:'Peso corporal' },
  { id:'seated-knee-tuck', nome:'Encolhimento sentado', grupo:'Abdómen', equip:'Peso corporal' },
  { id:'push-up-shoulder-tap', nome:'Flexão com toque no ombro', grupo:'Abdómen', equip:'Peso corporal' },
  { id:'dumbbell-side-bend', nome:'Flexão lateral com haltere', grupo:'Abdómen', equip:'Halteres' },
  { id:'hollow-body-hold', nome:'Hollow hold', grupo:'Abdómen', equip:'Peso corporal' },
  { id:'hollow-rock', nome:'Hollow rock', grupo:'Abdómen', equip:'Peso corporal' },
  { id:'l-sit-hold', nome:'L-sit', grupo:'Abdómen', equip:'Peso corporal' },
  { id:'inchworm', nome:'Lagarta', grupo:'Abdómen', equip:'Peso corporal' },
  { id:'banded-woodchop', nome:'Lenhador com elástico', grupo:'Abdómen', equip:'Elástico' },
  { id:'cable-woodchop', nome:'Lenhador na polia', grupo:'Abdómen', equip:'Polia' },
  { id:'bear-crawl', nome:'Marcha do urso', grupo:'Abdómen', equip:'Peso corporal' },
  { id:'half-burpee', nome:'Meio burpee', grupo:'Abdómen', equip:'Peso corporal' },
  { id:'cable-pallof-hold', nome:'Pallof isométrico na polia', grupo:'Abdómen', equip:'Polia' },
  { id:'pallof-press', nome:'Pallof press', grupo:'Abdómen', equip:'Polia' },
  { id:'banded-pallof-press', nome:'Pallof press com elástico', grupo:'Abdómen', equip:'Elástico' },
  { id:'half-kneeling-pallof-press', nome:'Pallof press meio ajoelhado', grupo:'Abdómen', equip:'Polia' },
  { id:'flutter-kick', nome:'Pernada alternada', grupo:'Abdómen', equip:'Peso corporal' },
  { id:'plank-jack', nome:'Prancha com salto', grupo:'Abdómen', equip:'Peso corporal' },
  { id:'plank-shoulder-tap', nome:'Prancha com toque no ombro', grupo:'Abdómen', equip:'Peso corporal' },
  { id:'copenhagen-plank', nome:'Prancha de Copenhaga', grupo:'Abdómen', equip:'Peso corporal' },
  { id:'bear-plank', nome:'Prancha do urso', grupo:'Abdómen', equip:'Peso corporal' },
  { id:'side-plank', nome:'Prancha lateral', grupo:'Abdómen', equip:'Peso corporal' },
  { id:'side-plank-hip-dip', nome:'Prancha lateral com descida da anca', grupo:'Abdómen', equip:'Peso corporal' },
  { id:'russian-twist', nome:'Rotação russa', grupo:'Abdómen', equip:'Peso corporal' },
  { id:'weighted-russian-twist', nome:'Rotação russa com peso', grupo:'Abdómen', equip:'Halteres' },
  { id:'squat-thrust', nome:'Squat thrust', grupo:'Abdómen', equip:'Peso corporal' },
  { id:'heel-tap', nome:'Toque nos calcanhares', grupo:'Abdómen', equip:'Peso corporal' },
  { id:'toe-touch', nome:'Toque nos pés', grupo:'Abdómen', equip:'Peso corporal' },
  { id:'v-up', nome:'V-up', grupo:'Abdómen', equip:'Peso corporal' },
  { id:'chin-up', nome:'Elevação na barra (pegada supinada)', grupo:'Bíceps', equip:'Peso corporal' },
  { id:'assisted-chin-up', nome:'Elevação supinada assistida', grupo:'Bíceps', equip:'Máquina' },
  { id:'weighted-chin-up', nome:'Elevação supinada com peso', grupo:'Bíceps', equip:'Peso corporal' },
  { id:'wrist-extension', nome:'Extensão de punhos', grupo:'Bíceps', equip:'Halteres' },
  { id:'wrist-curl', nome:'Flexão de punhos', grupo:'Bíceps', equip:'Barra' },
  { id:'drag-curl', nome:'Rosca arrastada', grupo:'Bíceps', equip:'Barra' },
  { id:'incline-dumbbell-curl', nome:'Rosca inclinada com halteres', grupo:'Bíceps', equip:'Halteres' },
  { id:'reverse-curl', nome:'Rosca inversa', grupo:'Bíceps', equip:'Barra' },
  { id:'rope-hammer-curl', nome:'Rosca martelo na polia', grupo:'Bíceps', equip:'Polia' },
  { id:'cable-curl', nome:'Rosca na polia', grupo:'Bíceps', equip:'Polia' },
  { id:'spider-curl', nome:'Rosca spider', grupo:'Bíceps', equip:'Halteres' },
  { id:'dead-hang', nome:'Suspensão na barra', grupo:'Bíceps', equip:'Peso corporal' },
  { id:'farmer-carry', nome:'Transporte do agricultor', grupo:'Bíceps', equip:'Halteres' },
  { id:'assault-bike', nome:'Air bike', grupo:'Cardio', equip:'Máquina', tipo:'cardio' },
  { id:'walking', nome:'Caminhada', grupo:'Cardio', equip:'Peso corporal', tipo:'cardio' },
  { id:'hiking', nome:'Caminhada na natureza', grupo:'Cardio', equip:'Peso corporal', tipo:'cardio' },
  { id:'swimming', nome:'Natação', grupo:'Cardio', equip:'Peso corporal', tipo:'cardio' },
  { id:'treadmill-incline-walk', nome:'Passadeira em inclinação', grupo:'Cardio', equip:'Máquina', tipo:'cardio' },
  { id:'skierg', nome:'SkiErg', grupo:'Cardio', equip:'Máquina', tipo:'cardio' },
  { id:'stair-climber', nome:'Stepper', grupo:'Cardio', equip:'Máquina', tipo:'cardio' },
  { id:'band-pull-apart', nome:'Abertura com elástico', grupo:'Costas', equip:'Elástico' },
  { id:'childs-pose', nome:'Alongamento da criança', grupo:'Costas', equip:'Peso corporal' },
  { id:'reverse-snow-angel', nome:'Anjo invertido', grupo:'Costas', equip:'Peso corporal' },
  { id:'assisted-pull-up', nome:'Elevação assistida na máquina', grupo:'Costas', equip:'Máquina' },
  { id:'neutral-grip-pull-up', nome:'Elevação com pegada neutra', grupo:'Costas', equip:'Peso corporal' },
  { id:'towel-pull-up', nome:'Elevação com toalha', grupo:'Costas', equip:'Peso corporal' },
  { id:'commando-pull-up', nome:'Elevação comando', grupo:'Costas', equip:'Peso corporal' },
  { id:'l-sit-pull-up', nome:'Elevação em L', grupo:'Costas', equip:'Peso corporal' },
  { id:'prone-t-raise', nome:'Elevação em T de bruços', grupo:'Costas', equip:'Peso corporal' },
  { id:'prone-y-raise', nome:'Elevação em Y de bruços', grupo:'Costas', equip:'Peso corporal' },
  { id:'scapular-pull-up', nome:'Elevação escapular', grupo:'Costas', equip:'Peso corporal' },
  { id:'weighted-pull-up', nome:'Elevação na barra com peso', grupo:'Costas', equip:'Peso corporal' },
  { id:'negative-pull-up', nome:'Elevação negativa', grupo:'Costas', equip:'Peso corporal' },
  { id:'shrug', nome:'Encolhimento com barra', grupo:'Costas', equip:'Barra' },
  { id:'back-extension', nome:'Extensão lombar', grupo:'Costas', equip:'Peso corporal' },
  { id:'banded-face-pull', nome:'Face pull com elástico', grupo:'Costas', equip:'Elástico' },
  { id:'face-pull', nome:'Face pull na polia', grupo:'Costas', equip:'Polia' },
  { id:'scapular-push-up', nome:'Flexão escapular', grupo:'Costas', equip:'Peso corporal' },
  { id:'trap-bar-deadlift', nome:'Levantamento terra com barra hexagonal', grupo:'Costas', equip:'Barra' },
  { id:'sumo-deadlift', nome:'Levantamento terra sumo', grupo:'Costas', equip:'Barra' },
  { id:'dumbbell-sumo-deadlift', nome:'Levantamento terra sumo com halteres', grupo:'Costas', equip:'Halteres' },
  { id:'banded-lat-pulldown', nome:'Puxada com elástico', grupo:'Costas', equip:'Elástico' },
  { id:'wide-grip-lat-pulldown', nome:'Puxada com pegada aberta', grupo:'Costas', equip:'Polia' },
  { id:'close-grip-lat-pulldown', nome:'Puxada com pegada fechada', grupo:'Costas', equip:'Polia' },
  { id:'rack-pull', nome:'Rack pull (terra parcial)', grupo:'Costas', equip:'Barra' },
  { id:'meadows-row', nome:'Remada Meadows', grupo:'Costas', equip:'Barra' },
  { id:'pendlay-row', nome:'Remada Pendlay', grupo:'Costas', equip:'Barra' },
  { id:'t-bar-row', nome:'Remada T', grupo:'Costas', equip:'Máquina' },
  { id:'chest-supported-row', nome:'Remada com apoio no peito', grupo:'Costas', equip:'Máquina' },
  { id:'banded-row', nome:'Remada com elástico', grupo:'Costas', equip:'Elástico' },
  { id:'towel-row', nome:'Remada com toalha', grupo:'Costas', equip:'Peso corporal' },
  { id:'dumbbell-bent-over-row', nome:'Remada curvada com halteres', grupo:'Costas', equip:'Halteres' },
  { id:'inverted-row', nome:'Remada invertida', grupo:'Costas', equip:'Peso corporal' },
  { id:'machine-row', nome:'Remada na máquina', grupo:'Costas', equip:'Máquina' },
  { id:'doorway-row', nome:'Remada na ombreira da porta', grupo:'Costas', equip:'Peso corporal' },
  { id:'single-arm-cable-row', nome:'Remada unilateral na polia', grupo:'Costas', equip:'Polia' },
  { id:'superman', nome:'Superman', grupo:'Costas', equip:'Peso corporal' },
  { id:'superman-hold', nome:'Superman isométrico', grupo:'Costas', equip:'Peso corporal' },
  { id:'active-hang', nome:'Suspensão ativa', grupo:'Costas', equip:'Peso corporal' },
  { id:'cross-body-shoulder-stretch', nome:'Alongamento de ombro cruzado', grupo:'Ombros', equip:'Peso corporal' },
  { id:'battle-ropes', nome:'Cordas de batalha', grupo:'Ombros', equip:'Acessório' },
  { id:'cable-rear-delt-fly', nome:'Crucifixo inverso na polia', grupo:'Ombros', equip:'Polia' },
  { id:'arm-circles', nome:'Círculos de braços', grupo:'Ombros', equip:'Peso corporal' },
  { id:'arnold-press', nome:'Desenvolvimento Arnold', grupo:'Ombros', equip:'Halteres' },
  { id:'standing-dumbbell-press', nome:'Desenvolvimento em pé com halteres', grupo:'Ombros', equip:'Halteres' },
  { id:'machine-shoulder-press', nome:'Desenvolvimento na máquina', grupo:'Ombros', equip:'Máquina' },
  { id:'landmine-press', nome:'Desenvolvimento no landmine', grupo:'Ombros', equip:'Barra' },
  { id:'plate-front-raise', nome:'Elevação frontal com disco', grupo:'Ombros', equip:'Acessório' },
  { id:'cable-front-raise', nome:'Elevação frontal na polia', grupo:'Ombros', equip:'Polia' },
  { id:'machine-lateral-raise', nome:'Elevação lateral na máquina', grupo:'Ombros', equip:'Máquina' },
  { id:'cable-lateral-raise', nome:'Elevação lateral na polia', grupo:'Ombros', equip:'Polia' },
  { id:'bent-over-rear-delt-raise', nome:'Elevação posterior curvado', grupo:'Ombros', equip:'Halteres' },
  { id:'handstand-push-up', nome:'Flexão em pino', grupo:'Ombros', equip:'Peso corporal' },
  { id:'wall-handstand-push-up', nome:'Flexão em pino na parede', grupo:'Ombros', equip:'Peso corporal' },
  { id:'pike-push-up', nome:'Flexão pique', grupo:'Ombros', equip:'Peso corporal' },
  { id:'feet-elevated-pike-push-up', nome:'Flexão pique com pés elevados', grupo:'Ombros', equip:'Peso corporal' },
  { id:'reverse-pec-deck', nome:'Peck deck inverso', grupo:'Ombros', equip:'Máquina' },
  { id:'push-press', nome:'Push press', grupo:'Ombros', equip:'Barra' },
  { id:'wall-walk', nome:'Subida à parede', grupo:'Ombros', equip:'Peso corporal' },
  { id:'doorway-chest-stretch', nome:'Alongamento de peito na porta', grupo:'Peito', equip:'Peso corporal' },
  { id:'incline-cable-fly', nome:'Crucifixo inclinado na polia', grupo:'Peito', equip:'Polia' },
  { id:'archer-push-up', nome:'Flexão archer', grupo:'Peito', equip:'Peso corporal' },
  { id:'wide-push-up', nome:'Flexão com mãos afastadas', grupo:'Peito', equip:'Peso corporal' },
  { id:'incline-push-up', nome:'Flexão com mãos elevadas', grupo:'Peito', equip:'Peso corporal' },
  { id:'weighted-push-up', nome:'Flexão com peso', grupo:'Peito', equip:'Peso corporal' },
  { id:'decline-push-up', nome:'Flexão com pés elevados', grupo:'Peito', equip:'Peso corporal' },
  { id:'knee-push-up', nome:'Flexão com joelhos apoiados', grupo:'Peito', equip:'Peso corporal' },
  { id:'explosive-push-up', nome:'Flexão explosiva', grupo:'Peito', equip:'Peso corporal' },
  { id:'hindu-push-up', nome:'Flexão hindu', grupo:'Peito', equip:'Peso corporal' },
  { id:'typewriter-push-up', nome:'Flexão máquina de escrever', grupo:'Peito', equip:'Peso corporal' },
  { id:'wall-push-up', nome:'Flexão na parede', grupo:'Peito', equip:'Peso corporal' },
  { id:'chest-dip', nome:'Mergulho nas paralelas (peito)', grupo:'Peito', equip:'Peso corporal' },
  { id:'seal-jack', nome:'Seal jack', grupo:'Peito', equip:'Peso corporal' },
  { id:'dumbbell-bench-press', nome:'Supino com halteres', grupo:'Peito', equip:'Halteres' },
  { id:'decline-dumbbell-press', nome:'Supino declinado com halteres', grupo:'Peito', equip:'Halteres' },
  { id:'incline-bench-press', nome:'Supino inclinado com barra', grupo:'Peito', equip:'Barra' },
  { id:'machine-chest-press', nome:'Supino na máquina', grupo:'Peito', equip:'Máquina' },
  { id:'smith-machine-bench-press', nome:'Supino no Smith', grupo:'Peito', equip:'Máquina' },
  { id:'side-lying-hip-abduction', nome:'Abdução da anca deitado', grupo:'Pernas', equip:'Peso corporal' },
  { id:'cable-standing-hip-abduction', nome:'Abdução da anca na polia', grupo:'Pernas', equip:'Polia' },
  { id:'fire-hydrant', nome:'Abdução de joelho', grupo:'Pernas', equip:'Peso corporal' },
  { id:'banded-fire-hydrant', nome:'Abdução de joelho com elástico', grupo:'Pernas', equip:'Elástico' },
  { id:'banded-standing-hip-abduction', nome:'Abdução em pé com elástico', grupo:'Pernas', equip:'Elástico' },
  { id:'banded-seated-hip-abduction', nome:'Abdução sentado com elástico', grupo:'Pernas', equip:'Elástico' },
  { id:'cable-standing-hip-adduction', nome:'Adução da anca na polia', grupo:'Pernas', equip:'Polia' },
  { id:'curtsy-lunge', nome:'Afundo cruzado', grupo:'Pernas', equip:'Peso corporal' },
  { id:'dumbbell-curtsy-lunge', nome:'Afundo cruzado com halteres', grupo:'Pernas', equip:'Halteres' },
  { id:'lateral-lunge', nome:'Afundo lateral', grupo:'Pernas', equip:'Peso corporal' },
  { id:'dumbbell-lateral-lunge', nome:'Afundo lateral com halteres', grupo:'Pernas', equip:'Halteres' },
  { id:'reverse-lunge', nome:'Afundo para trás', grupo:'Pernas', equip:'Halteres' },
  { id:'deficit-reverse-lunge', nome:'Afundo para trás em deficit', grupo:'Pernas', equip:'Halteres' },
  { id:'smith-machine-reverse-lunge', nome:'Afundo para trás no Smith', grupo:'Pernas', equip:'Máquina' },
  { id:'forward-lunge', nome:'Afundo à frente', grupo:'Pernas', equip:'Peso corporal' },
  { id:'belt-squat', nome:'Agachamento com cinto', grupo:'Pernas', equip:'Máquina' },
  { id:'banded-squat', nome:'Agachamento com elástico', grupo:'Pernas', equip:'Elástico' },
  { id:'jump-squat', nome:'Agachamento com salto', grupo:'Pernas', equip:'Peso corporal' },
  { id:'cossack-squat', nome:'Agachamento cossaco', grupo:'Pernas', equip:'Peso corporal' },
  { id:'skater-squat', nome:'Agachamento de patinador', grupo:'Pernas', equip:'Peso corporal' },
  { id:'front-squat', nome:'Agachamento frontal', grupo:'Pernas', equip:'Barra' },
  { id:'goblet-squat', nome:'Agachamento goblet', grupo:'Pernas', equip:'Halteres' },
  { id:'smith-machine-squat', nome:'Agachamento no Smith', grupo:'Pernas', equip:'Máquina' },
  { id:'landmine-squat', nome:'Agachamento no landmine', grupo:'Pernas', equip:'Barra' },
  { id:'pistol-squat', nome:'Agachamento numa perna', grupo:'Pernas', equip:'Peso corporal' },
  { id:'assisted-pistol-squat', nome:'Agachamento numa perna assistido', grupo:'Pernas', equip:'Peso corporal' },
  { id:'single-leg-box-squat', nome:'Agachamento numa perna no caixote', grupo:'Pernas', equip:'Peso corporal' },
  { id:'bodyweight-squat', nome:'Agachamento sem peso', grupo:'Pernas', equip:'Peso corporal' },
  { id:'shrimp-squat', nome:'Agachamento shrimp', grupo:'Pernas', equip:'Peso corporal' },
  { id:'split-squat', nome:'Agachamento split', grupo:'Pernas', equip:'Halteres' },
  { id:'dumbbell-sumo-squat', nome:'Agachamento sumo com haltere', grupo:'Pernas', equip:'Halteres' },
  { id:'butterfly-stretch', nome:'Alongamento borboleta', grupo:'Pernas', equip:'Peso corporal' },
  { id:'worlds-greatest-stretch', nome:'Alongamento completo', grupo:'Pernas', equip:'Peso corporal' },
  { id:'wall-calf-stretch', nome:'Alongamento de gémeos na parede', grupo:'Pernas', equip:'Peso corporal' },
  { id:'hamstring-stretch', nome:'Alongamento de isquiotibiais', grupo:'Pernas', equip:'Peso corporal' },
  { id:'standing-quad-stretch', nome:'Alongamento de quadríceps em pé', grupo:'Pernas', equip:'Peso corporal' },
  { id:'kneeling-hip-flexor-stretch', nome:'Alongamento do flexor da anca', grupo:'Pernas', equip:'Peso corporal' },
  { id:'seated-forward-fold-stretch', nome:'Alongamento sentado à frente', grupo:'Pernas', equip:'Peso corporal' },
  { id:'leg-swings-stretch', nome:'Balanços de perna', grupo:'Pernas', equip:'Peso corporal' },
  { id:'good-morning', nome:'Bom dia (good morning)', grupo:'Pernas', equip:'Barra' },
  { id:'burpee', nome:'Burpee', grupo:'Pernas', equip:'Peso corporal' },
  { id:'smith-machine-bulgarian-split-squat', nome:'Búlgaro no Smith', grupo:'Pernas', equip:'Máquina' },
  { id:'hip-adduction-machine', nome:'Cadeira adutora', grupo:'Pernas', equip:'Máquina' },
  { id:'wall-sit', nome:'Cadeira na parede', grupo:'Pernas', equip:'Peso corporal' },
  { id:'lying-hamstring-walkout', nome:'Caminhada de calcanhares deitado', grupo:'Pernas', equip:'Peso corporal' },
  { id:'banded-kickback', nome:'Coice com elástico', grupo:'Pernas', equip:'Elástico' },
  { id:'donkey-kick', nome:'Coice de glúteo', grupo:'Pernas', equip:'Peso corporal' },
  { id:'banded-donkey-kick', nome:'Coice de glúteo com elástico', grupo:'Pernas', equip:'Elástico' },
  { id:'machine-glute-kickback', nome:'Coice de glúteo na máquina', grupo:'Pernas', equip:'Máquina' },
  { id:'cable-kickback', nome:'Coice de glúteo na polia', grupo:'Pernas', equip:'Polia' },
  { id:'clamshell', nome:'Concha (clamshell)', grupo:'Pernas', equip:'Peso corporal' },
  { id:'banded-clamshell', nome:'Concha com elástico', grupo:'Pernas', equip:'Elástico' },
  { id:'nordic-hamstring-curl', nome:'Curl nórdico', grupo:'Pernas', equip:'Peso corporal' },
  { id:'step-down', nome:'Descida do caixote', grupo:'Pernas', equip:'Peso corporal' },
  { id:'lateral-shuffle', nome:'Deslocamento lateral', grupo:'Pernas', equip:'Peso corporal' },
  { id:'calf-raise', nome:'Elevação de gémeos', grupo:'Pernas', equip:'Peso corporal' },
  { id:'side-lying-leg-raise', nome:'Elevação de perna deitado de lado', grupo:'Pernas', equip:'Peso corporal' },
  { id:'banded-hip-thrust', nome:'Elevação pélvica com elástico', grupo:'Pernas', equip:'Elástico' },
  { id:'dumbbell-hip-thrust', nome:'Elevação pélvica com haltere', grupo:'Pernas', equip:'Halteres' },
  { id:'smith-machine-hip-thrust', nome:'Elevação pélvica no Smith', grupo:'Pernas', equip:'Máquina' },
  { id:'glute-focused-back-extension', nome:'Extensão lombar para glúteo', grupo:'Pernas', equip:'Peso corporal' },
  { id:'towel-hamstring-curl', nome:'Flexora com toalha', grupo:'Pernas', equip:'Peso corporal' },
  { id:'stability-ball-hamstring-curl', nome:'Flexora na bola suíça', grupo:'Pernas', equip:'Acessório' },
  { id:'leg-curl', nome:'Flexora na máquina', grupo:'Pernas', equip:'Máquina' },
  { id:'seated-leg-curl', nome:'Flexora sentado', grupo:'Pernas', equip:'Máquina' },
  { id:'cat-cow-stretch', nome:'Gato-camelo', grupo:'Costas', equip:'Peso corporal' },
  { id:'heel-elevated-goblet-squat', nome:'Goblet com calcanhares elevados', grupo:'Pernas', equip:'Halteres' },
  { id:'donkey-calf-raise', nome:'Gémeos donkey', grupo:'Pernas', equip:'Máquina' },
  { id:'leg-press-calf-raise', nome:'Gémeos na prensa', grupo:'Pernas', equip:'Máquina' },
  { id:'single-leg-calf-raise', nome:'Gémeos numa perna', grupo:'Pernas', equip:'Peso corporal' },
  { id:'seated-calf-raise', nome:'Gémeos sentado', grupo:'Pernas', equip:'Máquina' },
  { id:'hack-squat', nome:'Hack squat', grupo:'Pernas', equip:'Máquina' },
  { id:'reverse-hyperextension', nome:'Hiperextensão invertida', grupo:'Pernas', equip:'Máquina' },
  { id:'high-knees', nome:'Joelhos ao peito', grupo:'Pernas', equip:'Peso corporal' },
  { id:'banded-lateral-walk', nome:'Marcha lateral com elástico', grupo:'Pernas', equip:'Elástico' },
  { id:'banded-monster-walk', nome:'Marcha monstro com elástico', grupo:'Pernas', equip:'Elástico' },
  { id:'dumbbell-romanian-deadlift', nome:'Peso morto romeno com halteres', grupo:'Pernas', equip:'Halteres' },
  { id:'kettlebell-romanian-deadlift', nome:'Peso morto romeno com kettlebell', grupo:'Pernas', equip:'Kettlebell' },
  { id:'smith-machine-romanian-deadlift', nome:'Peso morto romeno no Smith', grupo:'Pernas', equip:'Máquina' },
  { id:'landmine-romanian-deadlift', nome:'Peso morto romeno no landmine', grupo:'Pernas', equip:'Barra' },
  { id:'single-leg-romanian-deadlift', nome:'Peso morto romeno numa perna', grupo:'Pernas', equip:'Halteres' },
  { id:'jumping-jack', nome:'Polichinelo', grupo:'Pernas', equip:'Peso corporal' },
  { id:'glute-bridge', nome:'Ponte de glúteos', grupo:'Pernas', equip:'Peso corporal' },
  { id:'barbell-glute-bridge', nome:'Ponte de glúteos com barra', grupo:'Pernas', equip:'Barra' },
  { id:'banded-glute-bridge', nome:'Ponte de glúteos com elástico', grupo:'Pernas', equip:'Elástico' },
  { id:'dumbbell-glute-bridge', nome:'Ponte de glúteos com haltere', grupo:'Pernas', equip:'Halteres' },
  { id:'glute-bridge-march', nome:'Ponte de glúteos com marcha', grupo:'Pernas', equip:'Peso corporal' },
  { id:'single-leg-glute-bridge', nome:'Ponte de glúteos numa perna', grupo:'Pernas', equip:'Peso corporal' },
  { id:'frog-pump', nome:'Ponte de rã', grupo:'Pernas', equip:'Peso corporal' },
  { id:'banded-frog-pump', nome:'Ponte de rã com elástico', grupo:'Pernas', equip:'Elástico' },
  { id:'cable-pull-through', nome:'Pull-through na polia', grupo:'Pernas', equip:'Polia' },
  { id:'fast-feet', nome:'Pés rápidos', grupo:'Pernas', equip:'Peso corporal' },
  { id:'hip-airplane', nome:'Rotação da anca em apoio único', grupo:'Pernas', equip:'Peso corporal' },
  { id:'torso-twist-stretch', nome:'Rotações de tronco', grupo:'Abdómen', equip:'Peso corporal' },
  { id:'skater-hop', nome:'Salto de patinador', grupo:'Pernas', equip:'Peso corporal' },
  { id:'sissy-squat', nome:'Sissy squat', grupo:'Pernas', equip:'Peso corporal' },
  { id:'front-foot-elevated-split-squat', nome:'Split squat com pé da frente elevado', grupo:'Pernas', equip:'Halteres' },
  { id:'smith-machine-split-squat', nome:'Split squat no Smith', grupo:'Pernas', equip:'Máquina' },
  { id:'sprawl', nome:'Sprawl', grupo:'Pernas', equip:'Peso corporal' },
  { id:'step-up', nome:'Subida ao caixote', grupo:'Pernas', equip:'Halteres' },
  { id:'kettlebell-swing', nome:'Swing com kettlebell', grupo:'Pernas', equip:'Kettlebell' },
  { id:'tricep-kickback', nome:'Coice de tríceps', grupo:'Tríceps', equip:'Halteres' },
  { id:'diamond-push-up', nome:'Flexão diamante', grupo:'Tríceps', equip:'Peso corporal' },
  { id:'crab-walk', nome:'Marcha do caranguejo', grupo:'Tríceps', equip:'Peso corporal' },
  { id:'chair-dip', nome:'Mergulho na cadeira', grupo:'Tríceps', equip:'Peso corporal' },
  { id:'assisted-dip', nome:'Paralelas assistidas', grupo:'Tríceps', equip:'Máquina' },
  { id:'weighted-dip', nome:'Paralelas com peso', grupo:'Tríceps', equip:'Peso corporal' },
  { id:'close-grip-bench-press', nome:'Supino com pegada fechada', grupo:'Tríceps', equip:'Barra' },
  { id:'overhead-tricep-extension', nome:'Tríceps acima da cabeça na polia', grupo:'Tríceps', equip:'Polia' },
  { id:'tricep-pushdown', nome:'Tríceps na polia (barra)', grupo:'Tríceps', equip:'Polia' },
  { id:'dumbbell-skull-crusher', nome:'Tríceps testa com halteres', grupo:'Tríceps', equip:'Halteres' },
  { id:'single-dumbbell-skullcrusher', nome:'Tríceps testa com um haltere', grupo:'Tríceps', equip:'Halteres' },
  { id:'single-arm-dumbbell-tricep-extension', nome:'Tríceps unilateral com haltere', grupo:'Tríceps', equip:'Halteres' },
].map(e => ({ tipo:'forca', ...e }));

/* Fichas sugeridas para quem abre o app pela primeira vez. */
const TREINOS_EXEMPLO = [
  {
    id:'t-push', nome:'A — Peito, Ombro e Tríceps', notas:'Empurrar',
    itens:[
      { exId:'suo-reto',      series:4, reps:8,  carga:0 },
      { exId:'sup-incl-hal',  series:3, reps:10, carga:0 },
      { exId:'desenvolv',     series:3, reps:10, carga:0 },
      { exId:'elev-lateral',  series:3, reps:12, carga:0 },
      { exId:'triceps-polia', series:3, reps:12, carga:0 },
    ]
  },
  {
    id:'t-pull', nome:'B — Costas e Bíceps', notas:'Puxar',
    itens:[
      { exId:'barra-fixa',    series:4, reps:8,  carga:0 },
      { exId:'remada-curv',   series:4, reps:10, carga:0 },
      { exId:'remada-baixa',  series:3, reps:12, carga:0 },
      { exId:'rosca-direta',  series:3, reps:10, carga:0 },
      { exId:'rosca-martelo', series:3, reps:12, carga:0 },
    ]
  },
  {
    id:'t-legs', nome:'C — Pernas e Abdómen', notas:'Inferiores',
    itens:[
      { exId:'agachamento',  series:4, reps:8,  carga:0 },
      { exId:'leg-press',    series:3, reps:12, carga:0 },
      { exId:'stiff',        series:3, reps:10, carga:0 },
      { exId:'flex-joelhos', series:3, reps:12, carga:0 },
      { exId:'panturrilha',  series:4, reps:15, carga:0 },
      { exId:'prancha',      series:3, reps:1,  carga:0 },
    ]
  },
];

/* ============================================================
   Catálogo de equipamento, para se escolher à mão o que existe
   no ginásio, em alternativa (ou em complemento) às fotos.
   ============================================================ */
const EQUIPAMENTOS = [
  { cat:'Pesos livres', itens:[
    { id:'barra',       nome:'Barra olímpica' },
    { id:'halteres',    nome:'Halteres' },
    { id:'kettlebell',  nome:'Kettlebells' },
    { id:'discos',      nome:'Discos / anilhas' },
    { id:'barra-ez',    nome:'Barra EZ' },
    { id:'landmine',    nome:'Landmine' },
    { id:'barra-hex',   nome:'Barra hexagonal' },
  ]},
  { cat:'Cabos e polias', itens:[
    { id:'crossover',   nome:'Crossover' },
    { id:'polia-alta',  nome:'Polia alta' },
    { id:'polia-baixa', nome:'Polia baixa' },
  ]},
  { cat:'Máquinas', itens:[
    { id:'m-leg-press', nome:'Leg press' },
    { id:'m-extensora', nome:'Cadeira extensora' },
    { id:'m-flexora',   nome:'Mesa flexora' },
    { id:'m-hack',      nome:'Hack squat' },
    { id:'m-smith',     nome:'Multipower (Smith)' },
    { id:'m-peck',      nome:'Peck deck' },
    { id:'m-supino',    nome:'Máquina de supino' },
    { id:'m-ombros',    nome:'Máquina de ombros' },
    { id:'m-puxada',    nome:'Puxada frontal' },
    { id:'m-remada',    nome:'Remada sentada' },
    { id:'m-abdutora',  nome:'Abdutora / adutora' },
    { id:'m-gemeos',    nome:'Máquina de gémeos' },
    { id:'m-gluteos',   nome:'Máquina de glúteos' },
    { id:'m-abdominal', nome:'Máquina abdominal' },
    { id:'m-multi',     nome:'Estação multifunções' },
  ]},
  { cat:'Bancos e suportes', itens:[
    { id:'banco',       nome:'Banco plano' },
    { id:'banco-incl',  nome:'Banco inclinado' },
    { id:'rack',        nome:'Rack de agachamento' },
    { id:'barra-fixa',  nome:'Barra fixa' },
    { id:'paralelas',   nome:'Paralelas' },
    { id:'espaldar',    nome:'Espaldar / cadeira romana' },
  ]},
  { cat:'Acessórios', itens:[
    { id:'elasticos',   nome:'Elásticos' },
    { id:'trx',         nome:'TRX / fitas de suspensão' },
    { id:'corda',       nome:'Corda de saltar' },
    { id:'bola',        nome:'Bola suíça' },
    { id:'roda',        nome:'Roda abdominal' },
    { id:'colchao',     nome:'Colchão' },
    { id:'caixa',       nome:'Caixa de saltos' },
  ]},
  { cat:'Cardio', itens:[
    { id:'passadeira',  nome:'Passadeira' },
    { id:'bicicleta',   nome:'Bicicleta' },
    { id:'eliptica',    nome:'Elíptica' },
    { id:'remo-erg',    nome:'Remo ergómetro' },
    { id:'escada',      nome:'Escada / stepper' },
    { id:'air-bike',    nome:'Air bike' },
  ]},
];

/* Nomes genéricos que os exercícios usam, e a peça do catálogo que os ilustra. */
const ALIAS_EQUIPAMENTO = {
  'barra':'barra', 'barra olimpica':'barra', 'halteres':'halteres',
  'maquina':'m-peck', 'polia':'polia-alta', 'acessorio':'elasticos',
  'elastico':'elasticos', 'elasticos':'elasticos', 'kettlebell':'kettlebell',
  'peso corporal':null, 'livre':null,
};

function chaveEquipamento(texto){
  return String(texto || '').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').trim();
}

const MAPA_EQUIPAMENTO = (() => {
  const mapa = {};
  for (const g of EQUIPAMENTOS) for (const it of g.itens) mapa[chaveEquipamento(it.nome)] = it.id;
  return mapa;
})();

/** id do catálogo a partir de um nome livre. Devolve null quando não há ilustração. */
function idEquipamento(nome){
  const k = chaveEquipamento(nome);
  if (k in ALIAS_EQUIPAMENTO) return ALIAS_EQUIPAMENTO[k];
  return MAPA_EQUIPAMENTO[k] || null;
}

const TOTAL_EQUIPAMENTOS = EQUIPAMENTOS.reduce((t, g) => t + g.itens.length, 0);

/** Nome legível a partir do id. */
function nomeEquipamento(id){
  for (const g of EQUIPAMENTOS){
    const i = g.itens.find(x => x.id === id);
    if (i) return i.nome;
  }
  return id;
}
